// swift-tools-version: 5.9
import PackageDescription

let package = Package(
    name: "libnfs",
    platforms: [.iOS(.v16), .tvOS(.v16), .macOS(.v13)],
    products: [
        .library(name: "libnfs", targets: ["libnfs"]),
    ],
    targets: [
        .target(
            name: "libnfs",
            path: ".",
            exclude: [
                "cmake",
                "tests",
                "examples",
                "doc",
                "packaging",
                "utils",
                "servers",
                "tls",
                "aros",
                "ps2_ee",
                "ps3_ppu",
                "win32",
                "m4",
                "CMakeLists.txt",
                "Makefile.am",
                "configure.ac",
                "bootstrap",
                "win32build.bat",
                "libnfs.pc.in",
                "COPYING",
                "CHANGELOG",
                "INSTALL",
                "README",
                "README.multithreading",
                "LICENCE-BSD.txt",
                "LICENCE-GPL-3.txt",
                "LICENCE-LGPL-2.1.txt",
                // Exclude CMakeLists.txt and Makefile.am in subdirectories
                "lib/CMakeLists.txt",
                "lib/Makefile.am",
                "lib/libnfs-win32.def",
                "lib/krb5-wrapper.c",
                "lib/krb5-wrapper.h",
                "mount/CMakeLists.txt",
                "mount/Makefile.am",
                "mount/mount.x",
                "nfs/CMakeLists.txt",
                "nfs/Makefile.am",
                "nfs/nfs.x",
                "nfs4/CMakeLists.txt",
                "nfs4/Makefile.am",
                "nfs4/nfs4.x",
                "nfs4/libnfs-raw-nfs4.c.fragment",
                "nfs4/libnfs-raw-nfs4.h.extra",
                "nfs/libnfs-raw-nfs.h.extra",
                "nlm/CMakeLists.txt",
                "nlm/Makefile.am",
                "nlm/nlm.x",
                "nsm/CMakeLists.txt",
                "nsm/Makefile.am",
                "nsm/nsm.x",
                "portmap/CMakeLists.txt",
                "portmap/Makefile.am",
                "portmap/portmap.x",
                "rquota/CMakeLists.txt",
                "rquota/Makefile.am",
                "rquota/rquota.x",
                // Exclude win32 compat header (not needed on Apple platforms)
                "include/win32",
            ],
            sources: [
                "lib",
                "mount",
                "nfs",
                "nfs4",
                "nlm",
                "nsm",
                "portmap",
                "rquota",
            ],
            publicHeadersPath: "include/nfsc",
            cSettings: [
                .headerSearchPath("include"),
                .headerSearchPath("include/nfsc"),
                .headerSearchPath("nfs"),
                .headerSearchPath("nfs4"),
                .headerSearchPath("mount"),
                .headerSearchPath("nlm"),
                .headerSearchPath("nsm"),
                .headerSearchPath("portmap"),
                .headerSearchPath("rquota"),
                .define("HAVE_ARPA_INET_H"),
                .define("HAVE_NETDB_H"),
                .define("HAVE_NETINET_IN_H"),
                .define("HAVE_NETINET_TCP_H"),
                .define("HAVE_NET_IF_H"),
                .define("HAVE_POLL_H"),
                .define("HAVE_PWD_H"),
                .define("HAVE_STRINGS_H"),
                .define("HAVE_SYS_IOCTL_H"),
                .define("HAVE_SYS_SOCKET_H"),
                .define("HAVE_SYS_STATVFS_H"),
                .define("HAVE_SYS_TIME_H"),
                // sys/vfs.h not available on Apple platforms
                .define("HAVE_UNISTD_H"),
                .define("HAVE_UTIME_H"),
                .define("HAVE_SOCKADDR_STORAGE"),
                .define("HAVE_SOCKADDR_LEN"),
                .define("HAVE_TALLOC_TEVENT"),
                .define("_U_", to: "__attribute__((unused))"),
            ]
        ),
    ]
)
